### ISSUE TITLE
Registry game detection

### ISSUE THREAD

**Issue by ZackCDLVI** [LRB-Game-Tools/Sims2Online#1]
Hey, LRB ~~guy who's supposed to be "closer to your goal" then me~~. Here's the info you needed on game detection.
https://github.com/NewSims2/NS2Patcher/wiki/Game-Detection
https://github.com/NewSims2/TheLab/tree/master/TS2DetectionTest

**Comment by LetsRaceBwoi** [comment]
I'm doing R&D, which is required for a project to be successful.  Nobody is closer to any goal since we're working on different projects, yours is TS3 and mine is TS2.  I'm not rivalling you, heck I'd try and help you if I could (but I'm busy with my own project).  I know what needs doing, and I'll start doing it.  But thanks for the heads up, I'll do it now :3

**Comment by ZackCDLVI** [comment]
> I'm doing R&D, which is required for a project to be successful.

I know that. I'm laying out the game detection framework first to make things easier on myself when it comes to my own R&D.

> Nobody is closer to any goal,

Music to my ears. I take back that my sentence.

> . I'm not rivalling you,

And I know your not. I like The Sims 2 too and decided that it's worth reverse engineering more then it is bothering with Sims 3. We may not be rivals but it still feels like friendly competition since we're both out to complete the same thing but in different ways.

> heck I'd try and help you if I could (but I'm busy with my own project)

I'm not asking anything from you. I'm just providing my two cents. This is will help you get you to your goal by giving you access to the installation directory ahead of time and save you the pain of putting a .package in your local directory or your app in the game's directory.

**Comment by LetsRaceBwoi** [comment]
>I forgot I wrote that

I see you're reading the thread!

>And I know you're not. I like The Sims 2 too and decided that it's worth reverse engineering more than it is bothering with Sims 3. We may not be rivals but it still feels like friendly competition since we're both out to complete the same thing but in different ways.

Who doesn't like TS2? I'm just making it online and giving it fixes.  You can have your own version at your own will, of course, it's just that I'm not going to rival anyone.

**Comment by ZackCDLVI** [comment]
> I see you're reading the thread!

*sighs* It's a public forum, dude. I was made aware of this from two of the people I know in the community. 

> Who doesn't like TS2? I'm just making it online and giving it fixes. You can have your own version at your own will, of course, it's just that I'm not going to rival anyone.

Fair enough.

**Comment by LetsRaceBwoi** [comment]
Fixed.
